### ISSUE TITLE
[Not an issue] Nice project

### ISSUE THREAD

**Issue by reallyuniquename** [PaaaulZ/PhotoViewerOutOfMemoryNoMore#2]
This is a neat solution, thanks for the write up! Just found the right jump and patched it. 

Any interesting tricks you used to narrow it down to `CreateMultiProfileTransform` call?

If at some point you decide to revisit this it is worth implementing a signature scan. Basically, a universal patch. Here is an example from a very similar project: https://github.com/mxs42/mutegram/blob/master/Mutegram/source/main.cpp

**Comment by PaaaulZ** [comment]
Thank you for your feedback! To narrow it down I put a breakpoint on every call to ThrowBase and just navigated the call stack to identify the function that was throwing the exception.

I tried implementing a sigscan but I'm having trouble finding a good signature, I'll keep trying and eventually update the project.

**Comment by reallyuniquename** [comment]
>I put a breakpoint on every call to ThrowBase

Do you mean just breaking on every exception?

**Comment by PaaaulZ** [comment]
Added signature scanning, thanks
